wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.24
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.10
    session_history: code/_session_history.ipynb
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 1
      - 2
      4: 3.7.10
      5: 0.10.24
      8:
      - 1
      - 5
architecture:
  desc: null
  value: ganin
batch_size:
  desc: null
  value: 64
classes:
  desc: null
  value: 10
dataset:
  desc: null
  value: mnist-mnist_m
epochs:
  desc: null
  value: 15
img_size:
  desc: null
  value: 28
learning_rate:
  desc: null
  value: 0.0002
